In [24]:
# 1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code 
# to print the data types of both the variables.
# import numpy as np
#  list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#  array_list = np.array(object = list_)
# Answer :-
# Yes, there is a difference in the data type of variables list_ and array_list.

# The variable list_ is a standard Python list, which can contain elements of different data types. In this case, it contains strings as elements.

# The variable array_list is a NumPy array, which is a homogeneous multidimensional container for elements of the same data type. When creating a NumPy array from a Python list, the data type of the resulting array is determined based on the elements of the list. In this case, since the elements of list_ are strings, the data type of array_list will be string as well.

# Here's the code to print the data types of both variables:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print("Data type of list_:", type(list_))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'list'>
Data type of array_list: <U1


In [25]:
# Q2. Write a code to print the data type of each and every element of both the variables list_ and 
# arra_list.
# import numpy as np
#  list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#  array_list = np.array(object = list_)
# Answer :-
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
for element in list_:
    print("Data type of element in list_:", type(element))

# Print data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list:", element.dtype)



Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <U1
Data type of element in array_list: <U1
Data type of element in array_list: <U1
Data type of element in array_list: <U1
Data type of element in array_list: <U1


In [26]:
# Q3. Considering the following changes in the variable, array_list:
#  array_list = np.array(object = list_, dtype = int)
# import numpy as np
#  list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
#  array_list = np.array(object = list_)
# Will there be any difference in the data type of the elements present in both the variables, list_ and 
# arra_list? If so then print the data types of each and every element present in both the variables, list_ 
# and arra_list.
# Answer :-
# Yes, there will be a difference in the data type of the elements present in both the variables list_ and array_list when the dtype parameter is explicitly set to int while creating array_list.
# Here's the updated code to print the data type of each element in both list_ and array_list:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
for element in list_:
    print("Data type of element in list_:", type(element))

# Print data type of each element in array_list
for element in array_list:
    print("Data type of element in array_list:", type(element))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>
Data type of element in array_list: <class 'numpy.int32'>


In [27]:
# Q4. Write a code to find the following characteristics of variable, num_array:
# (i) shape
# (ii) size
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#  num_array = np.array(object = num_list)
# Answer :-
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find the shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# Find the size of num_array
size = num_array.size
print("Size of num_array:", size)



Shape of num_array: (2, 3)
Size of num_array: 6


In [28]:
# Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array 
# creation function.
#  [Hint: The size of the array will be 9 and the shape will be (3,3).]
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#  num_array = np.array(object = num_list)
# Answer :-
import numpy as np

zero_array = np.zeros((3, 3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [29]:
# Q6. Create an identity matrix of shape (5,5) using numpy functions?
#  [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
# import numpy as np
# num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
#  num_array = np.array(object = num_list)
# Answer :-
import numpy as np

identity_matrix = np.eye(5)

print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
